server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  magic-link:
    base-url: ${MAGIC_LINK_BASE_URL:http://localhost:8081}
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    org.springframework.web: DEBUG
