apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-config
  namespace: eventsc
data:
  host: smtp.gmail.com
  port: "587"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: eventsc
type: Opaque
stringData:
  username: ""
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: eventsc
type: Opaque
stringData:
  secret: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db
  namespace: eventsc
type: Opaque
stringData:
  url: "jdbc:mysql://host.docker.internal:3306/event_sc?useSSL=false&serverTimezone=UTC"
  username: "root"
  password: "Wjz166605"
---
apiVersion: v1
kind: Secret
metadata:
  name: event-db
  namespace: eventsc
type: Opaque
stringData:
  url: "jdbc:mysql://host.docker.internal:3306/event_sc?useSSL=false&serverTimezone=UTC"
  username: "root"
  password: "Wjz166605"
