spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///event_sc?useSSL=false
    username: root
    password: myr021108-

  mail:
    host: smtp.gmail.com
    port: 587
    username: abbccdef3@gmail.com
    password: csci310fall24
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
